### ISSUE TITLE
[MC 1.20.x] Suggestion: Add support for campfire blockstates

### ISSUE THREAD

**Issue by winnetrie83** [alcatrazEscapee/no-tree-punching#269] opened 2023-10-21 11:11 UTC
Is it is possible to add to the config the following:

Wich block should be created when creating a campfire with blockstates supported.

This would help modpack makers. For example the mod "Unlit Campfire" adds burn timers to the campfire.
Notreepunching always create an infinite campfire.
It would be nice to have a config to change that state into false.

I already tried to do this with crafttweaker, but since the campfire created is not created by the player, i reach crafttweakers limitation.
It is a suggestion, not a demand ofcourse.

**Comment by alcatrazEscapee** [comment] 2023-10-21 11:12
Duplicate of #261

**Closed as not planned by alcatrazEscapee** 2023-10-21 11:12 UTC
Labels: duplicate
