### ISSUE TITLE
Compatability issue with Dynamic Trees

### ISSUE THREAD

**Issue by wiisafetymanual** [alcatrazEscapee/no-tree-punching#321] opened 2024-12-02 23:53 UTC
When playing with "doBlocksMineWithoutCorrectTool" set to true and "doBlocksDropWithoutCorrectTool" set to false with dynamic trees installed, trees still drop wood when mined without an axe. While this is only an issue when playing without the default config, I believe it is still important, because I, and I assume many other players, play with this config to prevent softlocking by getting stuck somewhere without a tool and not being able to mine out.

**Comment by alcatrazEscapee** [comment] 2024-12-03 00:08
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-12-03 00:08 UTC
