### ISSUE TITLE
Modded tools can't be used in crafts

### ISSUE THREAD

**Issue by dmitriy-8gears** [alcatrazEscapee/no-tree-punching#296] opened 2024-06-03 11:41 UTC
Is there any way to use modded axes for crafting planks and sticks? Axes from mOres isn't working.

Mod ver.: 6.0.0
MC ver.: 1.19.2

Update: Modded pickaxes can't mine ores

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:56
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:56 UTC
