### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by F4K3YT** [alcatrazEscapee/no-tree-punching#185] opened 2021-06-16 18:04 UTC
I'd like to know if there's any compatibility with the **biomes o plenty** mod (and **environmental**; basically, **any mod that adds new logs**), as i found out you can harvest logs, and **don't need a saw/axe to process them into wood planks** (again, only happens with wood from the mod); however, you do need the tool to convert planks to sticks, but if you could find a way to fix the logs->planks for biomes o plenty, or if there is any way in the config file, I'd like to know. Thanks for the mod though, brings a new challenge when starting a new game, really love it!
![1](https://user-images.githubusercontent.com/85964328/122269838-f2b56300-cedd-11eb-98d9-c36ac229bdd6.PNG)
![2](https://user-images.githubusercontent.com/85964328/122269841-f34df980-cedd-11eb-81c2-231d5f51327f.PNG)
![3](https://user-images.githubusercontent.com/85964328/122269842-f34df980-cedd-11eb-9616-d975bebce177.PNG)

**Comment by alcatrazEscapee** [comment] 2021-06-16 18:29
Duplicate of #127 

As an addendum to that issue, I am working on a automatic compatibility pass for several mods which add logs or otherwise cause problems with NTP's recipes, and I've got both those on my to-do list.

**Closed as completed by alcatrazEscapee** 2021-06-16 18:29 UTC
Labels: duplicate
