### ISSUE TITLE
[1.20.1] Plank and stick crafting only works with flint axe

### ISSUE THREAD

**Issue by polykatt** [alcatrazEscapee/no-tree-punching#302] opened 2024-08-05 03:39 UTC
I can't seem to make planks and sticks from logs using any other axe, only flint axe works. I'm not sure if this is intended or not but I tried with a stone axe and it does not work at all.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:56
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:56 UTC
