### ISSUE TITLE
Broken Knives Texture/Models

### ISSUE THREAD

**Issue by YisusClaus** [alcatrazEscapee/no-tree-punching#318] opened 2024-11-11 21:34 UTC
**Are the Knives textures/models supposed to be broken?**

![Knives](https://github.com/user-attachments/assets/23c7bdeb-9cd9-40d3-938d-a4b19b0de902)

**Tested on:**
- **_notreepunching-forge-1.20-7.1.0_**
- **_notreepunching-fabric-1.20-7.1.0_**

**Comment by alcatrazEscapee** [comment] 2024-11-30 07:19
Duplicate of #299

**Closed as not planned by alcatrazEscapee** 2024-11-30 07:19 UTC
Labels: duplicate
