### ISSUE TITLE
Flowers can't be obtained

### ISSUE THREAD

**Issue by SevieRedFur** [alcatrazEscapee/no-tree-punching#278] opened 2023-12-17 18:53 UTC
Hey there,

Flowers are unobtainable. I've tried every tool, swords, the knife, saws, axes, shovels, even shears. None of these tools drop the flowers.
I'm playing on the latest version of 1.20.1. 
I've played with this mod before on 1.19 and on that version it was the hoe. But nothing drops the flowers and the flowers are important to survive with the mashup of mods that I have. 

Thank you for your time.

**Comment by alcatrazEscapee** [comment] 2024-09-06 14:00
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 14:00 UTC
