### ISSUE TITLE
[Let's do] Vinery overwrites all plank wood crafing recipes

### ISSUE THREAD

**Issue by MailoDaPailo** [alcatrazEscapee/no-tree-punching#322] opened 2024-12-03 23:07 UTC
Vinery overwrites all plank recipes and only letting you craft apples log to planks with the axe. I think the issue is only with the axes, I didn't find any issue with the saw.

**Comment by alcatrazEscapee** [comment] 2024-12-03 23:09
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-12-03 23:09 UTC
