### ISSUE TITLE
Can't create planks

### ISSUE THREAD

**Issue by nshardy** [alcatrazEscapee/no-tree-punching#281] opened 2023-12-27 21:07 UTC
Background:
I started a new hardcore survival world, the recipes for creating planks are shown as sticks, so I can't make any form of planks.

I looked in `Common/src/main/java/com/alcatrazescapee/notreepunching/common/items/ModItems.java` to see if the new Flint Axe was registered as an AxeItem, or a ModAxeItem so it'll have custom interactions or properties.

There's also the issue of trying to create planks from any kind of log and an axe, the immediate recipe shown to the player is for sticks, not planks.

Solution:
My recommendation is to either add the custom functionality for the axes themselves (like right clicking on stripped logs to drop 4 planks, or 16 planks if it's the 6-sided log texture, since it uses 4 logs to make it), or change the recipes (like using planks and an axe to create sticks instead of regular logs and an axe to make sticks). The latter probably being the easier option, or assigning someone to this issue.

**Comment by definitelynotklip** [comment] 2024-01-29 15:27
You are able to make planks if you place the Flint Axe directly _above_ the log in the crafting grid, not next to it. If you place it next to the log in a horizontal configuration, you'll make sticks. Although this suggestion can be expanded to be able to do this with all axes, since doing this is only available for the Flint Axe - after that you can only use a Saw, rather than any other type of Axe.

**Comment by Skellykenz** [comment] 2024-06-17 19:17
you gotta put the axe on top the log

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:56
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:56 UTC
