### ISSUE TITLE
Cannot Craft Planks

### ISSUE THREAD

**Issue by cooper59** [alcatrazEscapee/no-tree-punching#263] opened 2023-09-04 23:53 UTC
When I try to craft planks using an axe it makes 6 sticks. 1.20.1 version

**Comment by cooper59** [comment] 2023-09-04 23:54
nvm

**Comment by Komi-ram** [comment] 2023-09-05 04:30
Apologize for asking, but how did you solve this? I'm currently stuck unable to figure out how to make planks. Thanks!

**Comment by cooper59** [comment] 2023-09-10 20:42
This is weird. So I looked at the other comments and somehow I put in the crafting table a certain way and it worked. Now it doesn't again..

**Comment by cooper59** [comment] 2023-09-10 20:49
I put the axe back above the logs but now it only works with one mod's wood

**Comment by cooper59** [comment] 2023-09-10 20:56
*It works with some logs but not others. Like I can't craft planks out of oak jungle or cherry logs

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:57
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:57 UTC
