### ISSUE TITLE
Axes can't make planks??

### ISSUE THREAD

**Issue by TheSexyYeti** [alcatrazEscapee/no-tree-punching#303] opened 2024-08-06 02:54 UTC
using the axes in the 2x2 crafting grid in the inventory won't let me make planks. Even though in JEI, it says you can. Even though JEI says it can be done in the crafting table. But i would think it should still work in the inventory crafting grid as well. but it doesn't. Even the configs say it should. what's the deal?.

**Comment by BeastSlayer666** [comment] 2024-08-15 04:00
I've had the same issue. So far just with _oak_ planks.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:57
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:57 UTC
