### ISSUE TITLE
Knives are missing the "Knife" tag?

### ISSUE THREAD

**Issue by leftbones** [alcatrazEscapee/no-tree-punching#274] opened 2023-11-17 16:40 UTC
I'm using both No Tree Punching and [Butcher's Delight](https://www.curseforge.com/minecraft/mc-mods/butchers-delight) in my modpack.

In Butcher's Delight, you can place an animal carcass on a flat surface and use any item with the "Knife" tag (according to the above link) to process the animal. This works with the fillet knives from Aquaculture, for example, but not with any of the knives from No Tree Punching.

Considering this is probably a very easy fix, I'll probably make a PR myself when I have the time, unless it's already done by then.

**Comment by alcatrazEscapee** [comment] 2024-09-06 14:04
Duplicate of #300

**Closed as not planned by alcatrazEscapee** 2024-09-06 14:04 UTC
