### ISSUE TITLE
Can you separate the setting "breaking speed" and "block drops" in config files?

### ISSUE THREAD

**Issue by MicroNeutron** [alcatrazEscapee/no-tree-punching#280] opened 2023-12-26 23:42 UTC
I cant get any drop from mining by mods' tools (maybe because there were not registered as a pickaxe). I still want the function that banned to get wood directly by hand. But you put them together in config files. And I cant control these functions seperately.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:59
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:59 UTC
