### ISSUE TITLE
No Tree Punching and Project: Vibrant Journeys hollow logs

### ISSUE THREAD

**Issue by Just2UesGitHub** [alcatrazEscapee/no-tree-punching#324] opened 2024-12-11 13:40 UTC
Project: Vibrant hollow log is used for planks instead of normal logs:(
![gwagr ty](https://github.com/user-attachments/assets/474f0cbf-8157-4a4b-9611-1837ef339a09)

**Comment by alcatrazEscapee** [comment] 2024-12-11 14:43
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-12-11 14:43 UTC
