### ISSUE TITLE
The Plant fiber chance drop too low 

### ISSUE THREAD

**Issue by himansure** [alcatrazEscapee/no-tree-punching#286] opened 2024-01-06 02:41 UTC
I use flint knives to break grass, but I break over 30 tall grass but not drop plant fiber, did you any plant add chance to drop in 1.20.1 like 1.12.2?

**Comment by alcatrazEscapee** [comment] 2024-09-06 14:06
Duplicate of #309 , more likely an issue caused by loot table override order.

**Closed as not planned by alcatrazEscapee** 2024-09-06 14:06 UTC
