### ISSUE TITLE
Aether + Addons No Dynamic Recipes

### ISSUE THREAD

**Issue by Amerith** [alcatrazEscapee/no-tree-punching#287] opened 2024-02-04 21:43 UTC
This is on 1.20.1 Forge. I'm not sure if this is on this mod's end or The Aether's. But with dynamic recipes on wood types from the Aether, Deep Aether, or Aether Redux just have standard log to plank recipes.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:56
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:56 UTC
