### ISSUE TITLE
[Possible bug] Log recipe discrepancy

### ISSUE THREAD

**Issue by Catomax262** [alcatrazEscapee/no-tree-punching#320] opened 2024-11-30 04:48 UTC
It's been an issue that dynamic compatibility for planks and logs is extremely hard to achieve.
A recent update mentions tag-based compatibility for plank balance.
However, with the recent update, I see that it kinda remains unchanged.

For example, non-compatible mods' planks' recipe should look like this.
![2024-11-29_23 30 40](https://github.com/user-attachments/assets/5a5dec70-2cfe-4c52-988d-19410e6b9a0c)

For example, mangrove logs are vanilla, but the respective recipes are thought of 1.18 and lower.
![2024-11-29_23 30 01](https://github.com/user-attachments/assets/81e21b42-55b1-4c66-94be-0a419d80527a)

And this is the mod's intended recipes.
![2024-11-29_23 32 07](https://github.com/user-attachments/assets/9cfc43d8-c2d8-4898-bff8-489eb3854af7)

It doesn't even get mentioned in the config...
![Captura de pantalla 2024-11-29 234458](https://github.com/user-attachments/assets/0ee89ea7-4d0d-430d-92bf-80cfbbe1e9a5)

I suggest a fix to this issue gets worked on ASAP.

**Comment by alcatrazEscapee** [comment] 2024-11-30 07:17
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-11-30 07:17 UTC
Labels: duplicate

**Comment by Catomax262** [comment] 2024-11-30 08:05
The config for the newest update option has not been properly implemented yet, that's why I wrote this thread.

Well, at least in the latest 1.19 version.
