### ISSUE TITLE
Create incompatiblity

### ISSUE THREAD

**Issue by Mlig317** [alcatrazEscapee/no-tree-punching#315] opened 2024-11-05 06:22 UTC
I'm not sure why but fabric 1.20.1, no tree punching + create results in being unable to cut grass with a knife. Like the block breaks but you never get plant fibers

**Comment by Mlig317** [comment] 2024-11-05 08:55
sorry, thats incompatibility with farmers delight, not create

**Comment by alcatrazEscapee** [comment] 2024-11-05 12:57
Duplicate of #309

**Closed as completed by alcatrazEscapee** 2024-11-05 12:57 UTC

**Comment by Mlig317** [comment] 2024-11-07 06:29
This is to say what exactly? that I need to create my own datapack if i want notreepunching to work with farmers delight?
