### ISSUE TITLE
Cannot farm crops

### ISSUE THREAD

**Issue by Bredosen** [alcatrazEscapee/no-tree-punching#298] opened 2024-06-22 08:36 UTC
So I just tried out the no-tree-punching (NTP) mod for the first time.

And I wanted to farm to crops, I've tried, knife, hands, axe, pickaxe, hoe, shears & macuahuitl. So far none of them give me my crops?

I've checked out the config file, and I've seen I can disable this, but then it would also disable it for every other block, and then I do not really see the point of this mod.

Is this a bug? or is there another tool I should use?

I use fabric 1.20.1 and NTP version 7.1.0

**Comment by asikwus** [comment] 2024-08-04 16:12
I seem to have the same issue. Forge 47.3.0 and the same NTP version (7.1.0)

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:58
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:58 UTC
