### ISSUE TITLE
Flowers obtainable without hoe

### ISSUE THREAD

**Issue by xeaal** [alcatrazEscapee/no-tree-punching#262] opened 2023-08-17 11:11 UTC
Hello. Can you please make it so that flowers are obtainable without a hoe? I am playing with a mod that requires flowers to make healing items and just couldn't get any before I could get a hoe. I can understand needing a knife or shears (better both of them, being interchangeable) but not hoe! You can just make it so you can use all of these three items, knife, shears and a hoe to get flowers.

**Comment by leftbones** [comment] 2023-11-17 16:42
I second this suggestion, I can pick flowers in real life without any tools if I harness the raw muscular power required to do so

**Comment by Arcirion** [comment] 2024-03-26 10:35
Even with a hoe small flowers don't drop anything? How do you get it to work?

**Comment by alcatrazEscapee** [comment] 2024-09-06 14:00
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 14:00 UTC
