### ISSUE TITLE
Ice & Fire - damaged axes don't register

### ISSUE THREAD

**Issue by luxlacis** [alcatrazEscapee/no-tree-punching#77] opened 2019-09-23 20:10 UTC
Using the mod ice and fire version 1.8.1, all of their axes when damaged don't register as axes. This means I can't chop down logs and get the drop and I can't right click on the logs to make them into planks.

**Comment by alcatrazEscapee** [comment] 2019-09-23 20:16
That's most likely because they don't register the items with the correct wildcard ore dictionary value. You can add that yourself via craft tweaker - it will work with `toolAxe` or `toolWeakAxe` respectively

**Comment by luxlacis** [comment] 2019-09-23 22:01
Sorry, I'm quite new to CraftTweaker. Are you able to give me an example of how I can do this please?

**Comment by Tommsy64** [comment] 2019-09-24 08:14
Here's an example with Tinker's Construct. Just replace `<tconstruct:hatchet:*>` with the resource ID of ice/fire axes. Make sure to keep the `:*` at the end to match all damage values of the item.
```
val toolAxe = <ore:toolAxe>;
val hatchet = <tconstruct:hatchet:*>;
toolAxe.add(hatchet);
```

**Comment by luxlacis** [comment] 2019-09-24 08:18
> Here's an example with Tinker's Construct. Just replace `<tconstruct:hatchet:*>` with the resource ID of ice/fire axes. Make sure to keep the `:*` at the end to match all damage values of the item.
> 
> ```
> val toolAxe = <ore:toolAxe>;
> val hatchet = <tconstruct:hatchet:*>;
> toolAxe.add(hatchet);
> ```

Thanks a lot!

**Comment by luxlacis** [comment] 2019-09-24 08:59
I've found another issue where modded axes (from ice and fire) do not chop & drop any minecraft logs. This extends to dynamic trees as well, i cannot chop them down with modded axes. I've extended the axes to the ore dictionary, but still same issue.

 However they do chop down modded logs (not dynamic trees) like fir wood from Traverse, but they do not chop down any dynamic trees from what i can tell. I also add the fir log to the logWood dictionary and still the same issue. I can also craft fir wood logs into in the crafting table.

**Comment by alcatrazEscapee** [comment] 2019-09-26 15:48
There's two things here:
 - If an axe isn't chopping down logs (i.e. breaking slowly, not dropping anything), then it's likely due to the mod author not properly adding the `axe` tool class to their tool. This is not something I can fix, it's on the other mod author to add the correct tool class. (It *may* be possible to do this with CT, but I'm not sure how to)
 - If a log block won't get chopped into planks, it's due to crafting recipes for the log -> wood missing. NTP will search for any recipes that match a `logWood`, getting transformed to any plank blocks. Either craft tweaker or adding json recipes should be able to fix this

**Comment by luxlacis** [comment] 2019-09-26 16:39
I extended the modded axe as toolAxe, as you said in crafttweaker but it's still the same issue. The traverse logs also are able to be crafted into planks. this video shows what's happening: https://www.youtube.com/watch?v=RkcFOlpA7oQ

**Comment by alcatrazEscapee** [comment] 2019-09-27 00:51
This is then 1) an ice and fire issue, and 2) a duplicate of #75

**Closed as completed by alcatrazEscapee** 2019-09-27 00:51 UTC

**Comment by Tommsy64** [comment] 2019-09-28 16:50
@luxlacis I ran into this issue with a modded Log -> Plank recipe. Even when adding both the log and planks to ore dictionary using CraftTweaker, the recipe without the saw remained.

The issue was that CraftTweaker was adding the log/planks to their respective ore dictionaries *after* NoTreePunching was doing its modifications to Log -> Plank recipes. I fixed this by writing a very small mod that adds the modded logs and planks to their ore dictionary before recipes are handled.

**Comment by luxlacis** [comment] 2019-09-28 17:19
@Tommsy64 where can I find this mod?

**Comment by alcatrazEscapee** [comment] 2019-09-28 17:56
FYI, this shouldn't be necessary in the latest version of NTP. I added another pass to catch Log -> Plank recipes added later in the initialization cycle. From my testing it works fine with traverse logs.

**Comment by luxlacis** [comment] 2019-09-30 20:12
> FYI, this shouldn't be necessary in the latest version of NTP. I added another pass to catch Log -> Plank recipes added later in the initialization cycle. From my testing it works fine with traverse logs.

Thank you!
