### ISSUE TITLE
Disable saws, and more config

### ISSUE THREAD

**Issue by Catomax262** [alcatrazEscapee/no-tree-punching#282] opened 2024-01-01 04:47 UTC
In my opinion, it's kinda bad how you literally need an IRON saw to make wood. That means, you literally have to mine iron ore with a flint pickaxe, which is extremely slow.

I don't know what is the purpose of crafting cobblestone with loose stones as stone tools are disabled.

Also, i have mods that add other kinds of small stones, but these are able to be insta-mined with hand but still need a pickaxe. That means you NEED a pickaxe to mine it.

It would be nice to be able to choose which blocks can be mined without tool and which ones need a tool.

**Comment by P4YN-Ki** [comment] 2024-04-17 02:44
I'm seconding this, I also have mods creating conflicts within my pack and being able to choose what gets enabled, would be nice.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:52
Duplicate of #309 for the majority of the report.

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:52 UTC
