### ISSUE TITLE
config ignored

### ISSUE THREAD

**Issue by ManFromTarkov** [alcatrazEscapee/no-tree-punching#249] opened 2023-05-03 09:23 UTC
Mod ignore edited configs

**Comment by alcatrazEscapee** [comment] 2023-05-03 11:36
Duplicate of #234 , given minimal context.

**Closed as completed by alcatrazEscapee** 2023-05-03 11:36 UTC
Labels: duplicate

**Comment by ManFromTarkov** [comment] 2023-05-04 12:43
sorry for duplicate, but i don't understand how to fix it, context: mod is installed on my server, config files are avaiable but with my edits it changes nothing ...
