### ISSUE TITLE
Unable to break Plants in survival

### ISSUE THREAD

**Issue by Jasusss** [alcatrazEscapee/no-tree-punching#273] opened 2023-11-10 03:54 UTC
I have seen a similar issue, but difference being that I'm on 1.20.1 using 7.1.0 on NTP. tested with axe, and didn't dropped the cherry blossom petals (or flowers, idk which is correct)

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:47
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:47 UTC
