### ISSUE TITLE
No tool harvests small flowers

### ISSUE THREAD

**Issue by Arcirion** [alcatrazEscapee/no-tree-punching#292] opened 2024-03-26 10:38 UTC
Previous posts mention a hoe can harvest small flowers but this no longer seems to be the case. I can't find a single way in survival mode to harvest small flowers.

**Comment by Midnight-GHub** [comment] 2024-05-09 03:46
Facing the same issue in fabric-1.20-7.1.0

**Comment by vainangel** [comment] 2024-06-20 05:56
Same issue on Forge-1.20.1-7.1.0

**Comment by ginsm** [comment] 2024-06-20 08:23
There's a config file (`notreepunching.toml`), at least for Fabric 1.20.1-7.1.0, that allows you to change this behavior. Set `doInstantBreakBlocksDropWithoutCorrectTool` to `true` and the flowers will drop their items again.

EDIT: This also works for modded plants (#272). This likely works as a workaround for #273, #264, and #290 as well.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:47
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:47 UTC
