### ISSUE TITLE
Axes Unable to cut Logs Into Planks

### ISSUE THREAD

**Issue by Derpercoaster** [alcatrazEscapee/no-tree-punching#194] opened 2021-07-04 04:34 UTC
It seems that instead of cutting logs into planks, axes just strip the bark off instead. It is completely impossible to get around this issue without using commands, so I am basically stuck.

**Comment by alcatrazEscapee** [comment] 2021-07-04 13:08
Duplicate of #181

**Closed as completed by alcatrazEscapee** 2021-07-04 13:08 UTC
