### ISSUE TITLE
doBlocksMineWithoutCorrectTool = false not working

### ISSUE THREAD

**Issue by ghost** [alcatrazEscapee/no-tree-punching#267] opened 2023-09-22 14:53 UTC
doBlocksMineWithoutCorrectTool = false does not work with any blocks and I'm still able to break them punching (though without drops which is good). When creating a different modpack it prevented me from breaking blocks just fine and I'm not sure what's causing the problem. Any idea if something could be interfering with it and how? Just wondering if there's anything I can do to make the feature work correctly, but I can't figure out what kind of mod could cause it

_Originally posted by @Fjuto in https://github.com/alcatrazEscapee/no-tree-punching/issues/266#issuecomment-1731531175_
            
Thought I should make a new issue as the previous one was completed and I didn't word this problem correctly, the issue is with vanilla blocks this time

CurseForge Fabric MC 1.20.1

**Comment by ghost** [comment] 2023-09-27 02:38
weird, was playing around adding and removing some mods and it's all working again. I'll drop another comment if I ever find out what exact mod was the cause

**Comment by ghost** [comment] 2023-09-27 04:29
yoooo turns out it's the Artifacts mod - https://www.curseforge.com/minecraft/mc-mods/artifacts
no idea how or why but the problem happens when it is added

**Comment by alcatrazEscapee** [comment] 2024-09-06 14:03
Duplicate of #309

**Closed as not planned by alcatrazEscapee** 2024-09-06 14:03 UTC
