### ISSUE TITLE
Unable to craft logs without specific type of wood

### ISSUE THREAD

**Issue by ClarenceAisle** [alcatrazEscapee/no-tree-punching#276] opened 2023-12-06 03:11 UTC
I am simply unable to craft logs without one specific type of wood, is there a way to work around this or add more than one recipe? I find it quite annoying how I have to travel over 3000 blocks to a completely different biome just to progress.

**Comment by alcatrazEscapee** [comment] 2024-09-06 13:56
Duplicate of #310

**Closed as not planned by alcatrazEscapee** 2024-09-06 13:56 UTC
